### ISSUE TITLE
Please update Bouncy Castle

### ISSUE THREAD

**Issue by Neustradamus** [tuxtor/microjwt-provider#2]
Please update Bouncy Castle
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncy%20castle
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncycastle
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by tuxtor** [comment]
Fixed in e61e5053027f36d8703c82e24e1c77e914ee426f

Thanks for the report

**Comment by Neustradamus** [comment]
@tuxtor: Thanks a lot!

**Comment by Neustradamus** [comment]
@tuxtor: Can you update to 1.69?
There were CVEs.
